"""fix_caste_religion_fk_mooc_enrollment_fk_drop_duplicate_enrollment_fields

Revision ID: 067e01ad06bb
Revises: 74545f9ef2ea
Create Date: 2026-04-05 12:25:13.497864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067e01ad06bb'
down_revision: Union[str, None] = '74545f9ef2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('castes', sa.Column('religion_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('castes_caste_name_key'), 'castes', type_='unique')
    op.create_foreign_key(None, 'castes', 'religions', ['religion_id'], ['religion_id'])
    op.drop_column('enrollment_mapping', 'department')
    op.drop_column('enrollment_mapping', 'class')
    op.add_column('student_mooc_enrollments', sa.Column('enrollment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_mooc_enrollments', 'enrollment_mapping', ['enrollment_id'], ['enrollment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_mooc_enrollments', type_='foreignkey')
    op.drop_column('student_mooc_enrollments', 'enrollment_id')
    op.add_column('enrollment_mapping', sa.Column('class', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('enrollment_mapping', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'castes', type_='foreignkey')
    op.create_unique_constraint(op.f('castes_caste_name_key'), 'castes', ['caste_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('castes', 'religion_id')
    # ### end Alembic commands ###
