"""add_is_active_to_student_and_status_to_certificate

Revision ID: 74545f9ef2ea
Revises: 9accc0e10b6c
Create Date: 2026-04-05 12:01:09.276495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74545f9ef2ea'
down_revision: Union[str, None] = '9accc0e10b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_request', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('student_information', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_information', 'is_active')
    op.drop_column('certificate_request', 'status')
    # ### end Alembic commands ###
