"""Initial schema

Revision ID: 9accc0e10b6c
Revises: None
Create Date: 2026-04-01 00:02:10.005048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9accc0e10b6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line1', sa.String(length=100), nullable=False),
    sa.Column('line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('castes',
    sa.Column('caste_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caste_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('caste_id'),
    sa.UniqueConstraint('caste_name')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('mooc_courses',
    sa.Column('mooc_course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('provider_university', sa.String(length=150), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('credit_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mooc_course_id'),
    sa.UniqueConstraint('course_code', 'platform', name='unique_course_platform')
    )
    op.create_table('religions',
    sa.Column('religion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('religion_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('religion_id'),
    sa.UniqueConstraint('religion_name')
    )
    op.create_table('sis_audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('student_information',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('email_id', sa.String(length=100), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('roll_number', sa.String(length=20), nullable=True),
    sa.Column('abc_id', sa.String(length=20), nullable=True),
    sa.Column('eligibility_number', sa.String(length=20), nullable=True),
    sa.Column('prn_number', sa.String(length=20), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('total_academic_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_submitted_fee', sa.Integer(), nullable=True),
    sa.Column('total_pending_fee', sa.Integer(), nullable=True),
    sa.Column('scholarship_applied', sa.Boolean(), nullable=True),
    sa.Column('scholarship_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('apply_for_class', sa.String(length=50), nullable=True),
    sa.Column('student_photo', sa.String(length=255), nullable=True),
    sa.Column('applicant_signature', sa.String(length=255), nullable=True),
    sa.Column('last_qualifying_exam', sa.String(length=100), nullable=True),
    sa.Column('last_exam_seat_number', sa.String(length=20), nullable=True),
    sa.Column('last_exam_board', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('abc_id'),
    sa.UniqueConstraint('eligibility_number'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('prn_number'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('certificate_request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('last_academic_year', sa.String(length=20), nullable=True),
    sa.Column('last_year_result_copy', sa.String(length=255), nullable=True),
    sa.Column('current_fee_receipt', sa.String(length=255), nullable=True),
    sa.Column('last_fee_receipt', sa.String(length=255), nullable=True),
    sa.Column('admission_proof', sa.String(length=255), nullable=True),
    sa.Column('applicant_signature', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('enrollment_mapping',
    sa.Column('enrollment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('program', sa.String(length=100), nullable=True),
    sa.Column('class', sa.String(length=50), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.Column('academic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_table('student_addresses',
    sa.Column('student_address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("address_type IN ('permanent', 'current', 'guardian')", name='chk_address_type'),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.address_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('student_address_id')
    )
    op.create_table('student_demographics',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('religion_id', sa.Integer(), nullable=True),
    sa.Column('caste_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caste_id'], ['castes.caste_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.religion_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('student_family_details',
    sa.Column('family_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent1_name', sa.String(length=100), nullable=True),
    sa.Column('parent1_phone', sa.String(length=15), nullable=True),
    sa.Column('parent1_occupation', sa.String(length=100), nullable=True),
    sa.Column('parent1_photo', sa.String(length=255), nullable=True),
    sa.Column('parent2_name', sa.String(length=100), nullable=True),
    sa.Column('parent2_phone', sa.String(length=15), nullable=True),
    sa.Column('parent2_occupation', sa.String(length=100), nullable=True),
    sa.Column('guardian_type', sa.String(length=50), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_phone', sa.String(length=15), nullable=True),
    sa.Column('guardian_occupation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_table('student_mooc_enrollments',
    sa.Column('mooc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mooc_course_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('certificate_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mooc_course_id'], ['mooc_courses.mooc_course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('mooc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_mooc_enrollments')
    op.drop_table('student_family_details')
    op.drop_table('student_demographics')
    op.drop_table('student_addresses')
    op.drop_table('enrollment_mapping')
    op.drop_table('certificate_request')
    op.drop_table('student_information')
    op.drop_table('sis_audit_log')
    op.drop_table('religions')
    op.drop_table('mooc_courses')
    op.drop_table('categories')
    op.drop_table('castes')
    op.drop_table('addresses')
    # ### end Alembic commands ###
