"""add_family_emails_guardian_address_fk

Revision ID: be469b01d3f7
Revises: 067e01ad06bb
Create Date: 2026-04-05 12:28:44.745825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be469b01d3f7'
down_revision: Union[str, None] = '067e01ad06bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_family_details', sa.Column('parent1_email', sa.String(length=100), nullable=True))
    op.add_column('student_family_details', sa.Column('parent2_email', sa.String(length=100), nullable=True))
    op.add_column('student_family_details', sa.Column('guardian_email', sa.String(length=100), nullable=True))
    op.add_column('student_family_details', sa.Column('guardian_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_family_details', 'addresses', ['guardian_address_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_family_details', type_='foreignkey')
    op.drop_column('student_family_details', 'guardian_address_id')
    op.drop_column('student_family_details', 'guardian_email')
    op.drop_column('student_family_details', 'parent2_email')
    op.drop_column('student_family_details', 'parent1_email')
    # ### end Alembic commands ###
